"""empty message

Revision ID: f23274e1d37c
Revises: 50f2a45c0650
Create Date: 2025-06-11 16:14:10.756388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f23274e1d37c'
down_revision: Union[str, None] = '50f2a45c0650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('registration_url', sa.String(), nullable=True))
    op.alter_column('event', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('event', 'registration_url')
    # ### end Alembic commands ###
